spring.application.name=ServiceBooking

# --- Database ---
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Swagger & OpenAPI ---
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger

# --- JWT ---
jwt.secret=${JWT_SECRET:my-super-secret-key-which-is-at-least-64-characters-long-1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000} # 1 hour in ms

# --- File Uploads ---
file.upload-dir=${FILE_UPLOAD_DIR:uploads/}
